/**
 * Writes supabase/seed.sql from the current SQLite data (menu, toppings, Today's Special,
 * promotions, translations, shop settings) so Supabase starts with exactly what the site
 * serves today. Read-only on SQLite; safe to run while the API is up.
 *
 *   cd backend && npx tsx scripts/export-supabase-seed.ts            # → ../supabase/seed.sql
 *   cd backend && npx tsx scripts/export-supabase-seed.ts out.sql    # custom path
 *
 * Accounts (customers, staff) are NOT in seed.sql: they must be created through Supabase Auth
 * (see SUPABASE-SETUP.md §5.2 and §11.4).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { db } from "../src/db";
import { effectiveItems, loadSettings } from "../src/logic";
import type { CatMeta, ToppingMeta } from "../src/lib/types";

const out = resolve(process.argv[2] ?? "../supabase/seed.sql");

/* SQL literal helpers (standard_conforming_strings = on, the Postgres default) */
const q = (v: unknown): string =>
  v === null || v === undefined ? "null"
  : typeof v === "number" ? (Number.isFinite(v) ? String(v) : "null")
  : typeof v === "boolean" ? String(v)
  : `'${String(v).replace(/'/g, "''")}'`;
const j = (v: unknown) => (v === null || v === undefined ? "null" : `${q(JSON.stringify(v))}::jsonb`);
const arr = (v: readonly (string | number)[] | undefined, type: string) =>
  v && v.length ? `array[${v.map(q).join(", ")}]::${type}[]` : `'{}'::${type}[]`;
const slug = (s: string) =>
  s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const noDataUrl = (u?: string) => (u && !u.startsWith("data:") ? u : null); // data: URLs go to Storage, not the DB
const day = (d: string | undefined, end: boolean) =>
  !d ? null : d.includes("T") ? d : `${d} ${end ? "23:59:59" : "00:00"} Europe/Helsinki`;

const s = loadSettings();
const sql: string[] = [
  "-- Generated by backend/scripts/export-supabase-seed.ts — do not edit by hand; re-run the script.",
  `-- Source: backend/data/kuopio.db · ${new Date().toISOString()}`,
  "begin;",
];

/* categories */
const cats = db.prepare(`SELECT id, title, en, sort FROM categories ORDER BY sort`).all() as
  { id: string; title: string; en: string | null; sort: number }[];
for (const c of cats) {
  const meta: CatMeta = s.catMeta?.[c.id] ?? {};
  const order = s.catOrder?.indexOf(c.id) ?? -1;
  sql.push(
    `insert into public.categories (id, name_fi, name_en, photo_url, photo_alt_fi, photo_alt_en, sort_order, visible) values (` +
      [q(c.id), q(meta.nameFi ?? c.title), q(meta.nameEn ?? c.en ?? c.title), q(noDataUrl(meta.img)),
       q(meta.altFi), q(meta.altEn), q(order >= 0 ? order : c.sort), q(!meta.hidden)].join(", ") + ");"
  );
}

/* menu items (base rows + admin overrides, exactly what the price authority uses) */
const sortOf = new Map(
  (db.prepare(`SELECT id, sort FROM items`).all() as { id: string; sort: number }[]).map((r) => [r.id, r.sort])
);
const toppingItems: string[] = [];
let itemCount = 0;
for (const m of effectiveItems()) {
  const labels = m.prices.map((p) => p.label).join("|");
  const medPerhe = labels === "Med|Perhe";
  const single = m.prices.length === 1 && m.prices[0].label === "";
  const off = s.offItems?.[m.id];
  const top = m.mods?.find((g) => g.id === "top");          // build-your-own: Fantasia / Pannu
  const classic = /^pizza(\d)$/.exec(m.cat);                 // pizza1 … pizza5: N toppings included
  if (top || classic) toppingItems.push(m.id);                // every pizza can take extra toppings
  itemCount++;
  sql.push(
    `insert into public.menu_items (id, category_id, name_fi, name_en, description_fi, description_en, price_med, price_perhe, price_variants, photo_url, photo_alt_fi, photo_alt_en, available, sold_out_on, pre_order_only, available_days, preorder_cutoff, lead_time_hours, topping_tier_included, mods, tags, sort_order) values (` +
      [
        q(m.id), q(m.cat), q(m.nameFi ?? m.name), q(m.name), q(m.descFi ?? m.desc ?? null), q(m.desc ?? null),
        q(medPerhe || single ? m.prices[0].value : Math.min(...m.prices.map((p) => p.value))),
        q(medPerhe ? m.prices[1].value : null),
        medPerhe || single ? "null" : j(m.prices),
        q(noDataUrl(s.itemImages?.[m.id]?.src)), q(s.itemImages?.[m.id]?.altFi), q(s.itemImages?.[m.id]?.altEn),
        q(!off?.off), q(off?.offToday ?? null),
        q(m.availability?.mode === "preorder_only"), arr(m.availability?.days, "smallint"),
        j(m.availability?.preorderCutoff), q(m.availability?.leadTimeHours ?? null),
        q(top?.min ?? (classic ? Number(classic[1]) : 0)), j(m.mods ?? []), arr(m.tags, "text"), q(sortOf.get(m.id) ?? 0),
      ].join(", ") + ");"
  );
}

/* toppings + which build-your-own / pizza items offer them */
const offToppings = new Set(s.offOptions?.topping ?? []);
s.toppings.forEach((label, i) => {
  const meta: ToppingMeta = s.toppingMeta?.[label] ?? {};
  sql.push(
    `insert into public.toppings (id, name_fi, name_en, surcharge_med, surcharge_perhe, active, sort_order) values (` +
      [q(slug(label)), q(meta.fi ?? label), q(meta.en ?? null), q(meta.priceMed ?? 1), q(meta.pricePerhe ?? 2),
       q(!offToppings.has(label)), q(i)].join(", ") + ");"
  );
});
if (toppingItems.length && s.toppings.length)
  sql.push(
    `insert into public.item_toppings (item_id, topping_id) select i, t from unnest(${arr(toppingItems, "text")}) i cross join unnest(${arr(s.toppings.map(slug), "text")}) t;`
  );

/* Today's Special strip */
for (const t of s.todaysSpecials ?? []) {
  const type = t.discount != null ? "percent" : t.overridePrice != null ? "fixed_price" : null;
  sql.push(
    `insert into public.todays_special (id, menu_item_id, discount_type, discount_value, photo_override_url, label_fi, label_en, sort_order, active, active_from, active_to) values (` +
      [q(t.id), q(t.itemId), q(type), q(t.discount ?? t.overridePrice ?? null), q(noDataUrl(t.imageUrl)),
       q(t.textFi), q(t.textEn), q(t.sortOrder), q(t.active), q(t.start ?? null), q(t.end ?? null)].join(", ") + ");"
  );
}

/* promotions (offers) */
for (const o of s.offers ?? []) {
  sql.push(
    `insert into public.promotions (id, code, discount_type, discount_value, scope, min_order, days, starts_at, expires_at, usage_limit, used_count, title_fi, title_en, description_fi, description_en, badge_fi, badge_en, banner_url, priority, active) values (` +
      [q(o.id), q(o.code ?? null), q(o.type), q(o.value), j(o.scope), q(o.minOrder ?? null),
       o.days?.length ? arr(o.days, "smallint") : "null", q(day(o.start, false)), q(day(o.end, true)),
       q(o.maxUses ?? null), q(o.uses ?? 0), q(o.titleFi), q(o.titleEn), q(o.descFi ?? null), q(o.descEn ?? null),
       q(o.badgeFi ?? null), q(o.badgeEn ?? null), q(noDataUrl(o.banner?.src)), q(o.priority), q(o.active)].join(", ") + ");"
  );
}

/* UI strings: (lang, key, value) rows → one row per key */
const tr = db.prepare(`SELECT lang, key, value FROM translations`).all() as { lang: string; key: string; value: string }[];
const byKey = new Map<string, { en?: string; fi?: string }>();
for (const r of tr) (byKey.get(r.key) ?? byKey.set(r.key, {}).get(r.key)!)[r.lang as "en" | "fi"] = r.value;
for (const [key, v] of byKey)
  sql.push(`insert into public.translation_strings (key, value_en, value_fi) values (${q(key)}, ${q(v.en ?? v.fi)}, ${q(v.fi ?? null)});`);

/* shop settings (single row; the migration created it with defaults) */
sql.push(
  `insert into public.shop_settings (id, paused, pause_message, hours, delivery_fee, min_order, radius_km, vat_rate, preorder, blocked_dates, blocked_slots, announcement, extra) values (true, ` +
    [q(s.paused), q(s.pauseMessage ?? null), j(s.hours), q(s.deliveryFee), q(s.minOrder), q(s.radiusKm), q(s.vatRate),
     j(s.preorder), arr(s.blockedDates, "date"), arr(s.blockedSlots, "text"), j(s.announcement ?? { enabled: false, text: "" }),
     j({ headerLogo: s.headerLogo, hideUnavailable: s.hideUnavailable, platforms: s.platforms })].join(", ") +
    `) on conflict (id) do update set paused = excluded.paused, pause_message = excluded.pause_message, hours = excluded.hours, delivery_fee = excluded.delivery_fee, min_order = excluded.min_order, radius_km = excluded.radius_km, vat_rate = excluded.vat_rate, preorder = excluded.preorder, blocked_dates = excluded.blocked_dates, blocked_slots = excluded.blocked_slots, announcement = excluded.announcement, extra = excluded.extra;`
);

sql.push("commit;", "");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, sql.join("\n"));
console.log(
  `wrote ${out}: ${cats.length} categories, ${itemCount} items, ${s.toppings.length} toppings, ` +
    `${(s.todaysSpecials ?? []).length} specials, ${(s.offers ?? []).length} promotions, ${byKey.size} strings`
);
