import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto("http://localhost:3000/", { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
await page.screenshot({ path: "tmp/shots4/crisp-hero.png" });
await page.evaluate(() => window.scrollTo(0, 94));
await page.waitForTimeout(400);
await page.screenshot({ path: "tmp/shots4/crisp-boundary.png" });
await browser.close();
console.log("done");
