import { chromium } from "playwright";
const login = await fetch("http://localhost:4000/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: "testi@example.com", pass: "demo1234" }) }).then(r=>r.json());
const browser = await chromium.launch();
const ctx = await browser.newContext();
await ctx.addInitScript((d) => { localStorage.setItem("kb_token", d.token); localStorage.setItem("kb_user", JSON.stringify(d.user)); }, login.data);
const page = await ctx.newPage();
await page.goto("http://localhost:3000/menu?cat=kebab", { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
await page.locator("button:has-text('+')").first().click();
await page.waitForTimeout(300);
await page.locator("button:has-text('+')").first().click();
await page.waitForTimeout(600);
await page.goto("http://localhost:3000/order", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(2500);
const phone = page.locator("input[placeholder='Phone for order updates']");
if (await phone.count() && !(await phone.inputValue())) await phone.fill("0401234567");
const addr = page.locator("input[placeholder*='postal code']");
if (await addr.count() && !(await addr.inputValue())) await addr.fill("Maaherrankatu 12, 70100, Kuopio");
const cph = page.locator("input[placeholder='Phone for the courier']");
if (await cph.count() && !(await cph.inputValue())) await cph.fill("0401234567");
await page.waitForTimeout(1200);
const body = await page.locator("body").innerText();
console.log(body.split("\n").filter(l => /open|closed|paused|minimum|min|70\d{3}|postal|deliver|account|sign|log/i.test(l)).slice(0,15).join(" || "));
const pay = page.locator("button", { hasText: "Pay securely" });
console.log("pay disabled:", await pay.first().isDisabled());
await browser.close();
