import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto("http://localhost:3000/menu?cat=buckets", { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
await page.evaluate(() => window.scrollTo(0, 400));
await page.waitForTimeout(500);
await page.screenshot({ path: "tmp/shots4/menu-buckets2.png" });
await browser.close();
console.log("done");
